FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Fallball

Fallball solution is a test service, which provides you with such functionality as documents sharing, collaboration tools and so on.

## General Information Collection [/v1/]

### Get Fallball Service Information [GET]
    
+ Response 200 (application/json)

        [
            {
                "description": "Fallball API allows you manage resellers, companies, users" 
            }
        ]

## Resellers Collection [/v1/resellers/]

### List All Resellers [GET]
    
+ Response 200 (application/json)

        [
            {
                "name": "reseller_a", 
                "clients_amount": 25,
                "token": "35b77ce0-502f-11e4-9b31-25bca9fc0b20"
                "rid": "a66c2dd0-048d-452d-bbd7-50e78ff66e5d"
                "storage": {
                    "usage": "250",
                    "limit": 800
                }
            },
            {
                "name": "reseller_b",
                "clients_amount": 20,
                "rid": "a66c2dd0-048d-452d-bbd7-50e78ff66e5e"
                "token": "2dd5975f6d9c3199f702540925ba79572f6bf3e6",
                "storage": {
                    "usage": "203",
                    "limit": 500
                }
            }
        ]

### Create New Reseller [POST]

+ Request (application/json)

        {
            "name": "reseller_a",
            "rid": "a66c2dd0-048d-452d-bbd7-50e78ff66e5d",
            "storage": {
                "limit": 800
            }
        }


+ Response 200 (application/json)

        {
            "name": "reseller_a",
            "clients_amount": 0,
            "rid": "a66c2dd0-048d-452d-bbd7-50e78ff66e5d",
            "token": "2dd5975f6d9c3199f702540925ba79572f6bf3e6",
            "storage": {
                    "usage": 0,
                    "limit": 800
            }
        }

## Reseller collection [/v1/reseller/{reseller_name}/]

### Get Reseller Information [GET]

+ Response 200 (application/json)

        {
            "name": "reseller_a",
            "rid": "a66c2dd0-048d-452d-bbd7-50e78ff66e5d",
            "token": "35b77ce0-502f-11e4-9b31-25bca9fc0b20",
            "clients_amount": 25,
            "storage": {
                    "usage": 250,
                    "limit": 800
            }
        }

### Delete Reseller [DELETE]

+ Response 204

## Reset Reseller to Initial State Collection [/v1/resellers/{reseller_name}/reset/]

### Reset Reseller [GET]

+ Response 200 (application/json)

        [
            {
                "result": "true",
            }
        ]

## Clients Collection [/v1/resellers/{reseller_name}/clients/]

### List All Clients [GET]

+ Response 200 (application/json)

        [
            {
                "name": "client_a",
                "creation_date": "2016-03-22T06:12:27+00:00",
                "is_integrated": true,
                "users_amount": 12,
                "storage": {
                    "usage": 250,
                    "limit": 800
                }
            }
        ]

### Create New Client [POST]

+ Request (application/json)

        {
            "name": "client_a",
            "storage": {
                "limit": 200
            }
        }


+ Response 200 (application/json)

        {
            "name": "client_a",
            "is_integrated": false,
            "creation_date": "2016-03-22T06:12:27+00:00",
            "users_amount": 0,
            "storage": {
                    "usage": 250,
                    "limit": 800
            }
        }

### Delete Client [DELETE]

+ Response 204

## Client Collection [/v1/resellers/{reseller_name}/clients/{client_name}/]

### Get Client Information [GET]

+ Response 200 (application/json)

        {
            "name": "client_a",
            "creation_date": "2016-03-22T06:12:27+00:00",
            "is_integrated": false,
            "users_amount": 12,
            "storage": {
                    "usage": 250,
                    "limit": 800
            }
        }



### Delete Client [DELETE]

+ Response 204

## Users Collection [/v1/resellers/{reseller_name}/clients/{client_name}/users/]

### List All Users [GET]

+ Response 200 (application/json)

        [
            {
                "email": "john@company.com",
                "password": "D7H3kj8",
                "admin": true,
                "storage": {
                    "usage": 15,
                    "limit": 32
                }
            }
        ]


### Create New User [POST]

+ Request (application/json)

        {
            "email": "john@company.com",
            "admin": true
            "storage": {
                "limit": 200
            }
        }


+ Response 200 (application/json)

        {
            "email": "john@company.com",
            "password": "",
            "admin": true, 
            "storage": { 
                    "usage": "15", 
                    "limit": "32"
            }
        }

## User Collection [/v1/resellers/{reseller_name}/clients/{client_name}/users/{email}/]

### Get User Information [GET]

+ Response 200 (application/json)
        
        {
            "email": "john@company.com",
            "password": "D7H3kj8",
            "admin": true, 
            "storage": { 
                    "usage": "15", 
                    "limit": "32"
            }
        }
        
### Delete User [DELETE]

+ Response 204