version: '2'
services:
  fbdb:
    volumes:
      - "./dbvolume:/var/lib/mysql"
    container_name: fbdb
    image: mariadb:latest
    env_file:
     - database.env
    ports:
     - "3306:3306"
    expose:
     - "3306"
  app:
    build: .
    container_name: fallballapp
    env_file:
     - database.env
    command: dockerize -wait tcp://fbdb:3306 -timeout 30s python manage.py runserver 0.0.0.0:8002
    #command: python -m SimpleHTTPServer
    depends_on:
     - fbdb
    environment:
      MYSQL_HOST: fbdb
    ports:
     - "8002:8002"
    volumes:
     - "./fallball:/app"