# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-28 08:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fallballapp', '0003_clientuser_password_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='async',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='ready_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 1, 0, 0, 0, 0, tzinfo=utc)),
        ),
    ]
